#!/bin/bash
# 快速验证和使用指南

echo "=========================================="
echo "Mix 项目修复验证和使用指南"
echo "=========================================="
echo ""

echo "📋 步骤 1: 验证修复是否已应用"
echo "------------------------------------------"
echo "运行: python tools/verify_fixes.py"
echo ""
python tools/verify_fixes.py
echo ""

echo "📋 步骤 2: 查看详细报告"
echo "------------------------------------------"
echo "中文总结: cat 检查结果_中文总结.md | head -100"
echo "完整报告: cat DIAGNOSTIC_REPORT.md"
echo ""

echo "📋 步骤 3: 下一步操作建议"
echo "------------------------------------------"
echo ""
echo "选项 A: 重新评估现有 checkpoint"
echo "  目的: 看看之前的 best_model.pth 的真实 mIoU"
echo "  命令: python eval_model.py --checkpoint checkpoints/best_model.pth"
echo ""
echo "选项 B: 继续/重新训练"
echo "  目的: 使用修复后的代码训练"
echo "  命令: python train_open_vocab_v2_ddp.py --config your_config.yaml"
echo "  注意: 第一次训练会自动验证所有样本是否有预计算投影"
echo ""
echo "选项 C: 诊断和阈值扫描（可选）"
echo "  目的: 找到最佳评估阈值，可能提升 5-10% mIoU"
echo "  命令: python tools/diagnose_training_issues.py \\"
echo "         --config config/your_config.yaml \\"
echo "         --checkpoint checkpoints/best_model.pth"
echo ""

echo "=========================================="
echo "🎯 最关键的修复"
echo "=========================================="
echo ""
echo "Best model 保存策略已从「按 val_loss」改为「按 mIoU」"
echo ""
echo "影响:"
echo "  - 之前可能保存了错误的 checkpoint"
echo "  - 建议重新评估 best_model.pth"
echo "  - 可能会发现 mIoU 比之前记录的更高！"
echo ""

echo "=========================================="
echo "📚 相关文件"
echo "=========================================="
echo ""
echo "  检查结果_中文总结.md      - 中文简明总结"
echo "  DIAGNOSTIC_REPORT.md       - 完整英文报告"
echo "  tools/verify_fixes.py      - 验证修复"
echo "  tools/quick_code_check.py  - 快速代码检查"
echo "  tools/fix_patches.py       - 查看修复详情"
echo ""
